name: Build and Deploy .NET Application

env:
  AZURE_WEBAPP_NAME: myapp1212    
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '6.0'

on:
  push:
    branches:
      - feature/add_cicd_pipeline
    paths:
      - azure-app-service-vnet-template/Source/**  

jobs:
  build:
    name: build
    runs-on:  ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET SDK
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build
      - name: Restore dependencies and build application
        run: |
          dotnet restore
          dotnet build --no-restore -c Release
          dotnet publish -c Release --no-build -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Publish artifacts to repository location
        uses: actions/upload-artifact@v2.2.2
        with: 
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: 'Development'
      url: 'https://myapp1212.azurewebsites.net'    
  
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2.0.8
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Signing in to Azure
      - name: Signing in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # Deploy to Azure Web apps
      - name: Run Azure webapp deploy action using service principal
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
      - name: Logout
        run: |
          az logout