name: Build and Deploy .NET Application

env:
  AZURE_WEBAPP_NAME: 'webapp-template-app'    
  AZURE_PRODUCTION_WEBAPP_NAME: 'webapp-template-app-production'
  AZURE_WEBAPP_PACKAGE_PATH: './azure-app-service-vnet-template/Source/TodoApp/TodoApp.Portal/'
  DOTNET_VERSION: '6.0'
  DEV_APP_SERVICE_URL: 'https://webapp-template-app.azurewebsites.net'
  PRODUCTION_APP_SERVICE_URL: ''

on: 
  push:
    branches:
      - feature/add_cicd_pipeline

# on:
#   pull_request:
#     branches:
#       - master
#     paths:
#       - azure-app-service-vnet-template/Source/**  
#     types: 
#       - closed

jobs:
  build:
    # if: github.event.pull_request.merged == true
    name: build
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory: ./azure-app-service-vnet-template/Source/TodoApp/TodoApp.Portal
    steps:
      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET SDK
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build
      - name: Restore dependencies and build application
        run: |
          dotnet restore
          dotnet build --no-restore -c Release
          dotnet publish -c Release --no-build -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Publish artifacts to repository location
        uses: actions/upload-artifact@v2.2.2
        with: 
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-to-dev:
    needs: build
    runs-on: ubuntu-latest

    environment: 
      name: 'development'
      url: ${{ env.DEV_APP_SERVICE_URL }}

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2.0.8
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Signing in to Azure
      - name: Signing in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # Deploy to Azure Web apps
      - name: Run Azure webapp deploy action using service principal
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
      - name: Logout
        run: |
          az logout
    
  # deploy-to-production:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   environment: 
  #     name: 'production'
  #     url: ${{ env.PRODUCTION_APP_SERVICE_URL }}
    
  #   steps:
  #     - name: Download Build Artifacts
  #       uses: actions/download-artifact@v2.0.8
  #       with:
  #         name: webapp
  #         path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  #     # Signing in to Azure
  #     - name: Signing in to Azure
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_PRODUCTION_CREDENTIALS }}
          
  #     # Deploy to Azure Web apps
  #     - name: Run Azure webapp deploy action using service principal
  #       uses: azure/webapps-deploy@v2
  #       with: 
  #         app-name: ${{ env.AZURE_PRODUCTION_WEBAPP_NAME }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
  #     - name: Logout
  #       run: |
  #         az logout