on: 
  push:
    branches:
      - master
    paths:
      - azure-app-service-vnet-template/Infrastructure/**  

name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file 1
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        scope: subscription
        region: southeastasia
        template: ./azure-app-service-vnet-template/Infrastructure/main.bicep
        failOnStdErr: false
